### ISSUE TITLE
Password templates differ from other mpw implementations

### ISSUE THREAD

**Issue by bronger** [emiljoha/mpwalg#1]
I use https://play.google.com/store/apps/details?id=de.devland.masterpassword and it generates differing passwords from your implementation. Moreover, https://gitlab.com/spectre.app/api/-/blob/main/c/spectre-types.c contains different patterns.

**Comment by emiljoha** [comment]
Thank you for reporting this!

You are right, both the "original" project source code and the pdf specifiation that I used to implement my version https://masterpassword.app/masterpassword-algorithm.pdf have different templates....

**Comment by emiljoha** [comment]
Solved  by @bronger himself in #2 

Thank you!

**Comment by emiljoha** [comment]
Fixed in version 0.2.
